# Generated by Django 5.1.2 on 2025-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_of_study_alter_student_current_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='grade_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cat',
            name='letter_grade',
            field=models.CharField(default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='cat',
            name='position',
            field=models.CharField(default='Fail', max_length=20),
        ),
    ]
