# Generated by Django 5.1.2 on 2025-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='category',
            field=models.CharField(choices=[('Education', 'Education')], max_length=50),
        ),
    ]
