# Generated by Django 5.1.2 on 2025-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, default='teachers_profiles/profile.png', null=True, upload_to='teachers_profiles/'),
        ),
    ]
