# Generated by Django 5.1.2 on 2025-03-21 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_feepayment_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subjects', to='myapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='myapp.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subjects', to='myapp.term')),
            ],
            options={
                'unique_together': {('student', 'term', 'subject')},
            },
        ),
    ]
