# Generated by Django 5.1.2 on 2025-03-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_examinationsession_resourcecategory_examtimetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ABSENT', 'Absent'), ('LATE', 'Late Reporting')], default='REPORTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='myapp.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.term')),
            ],
            options={
                'ordering': ['-term__year', 'term__name', 'reporting_date'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
