# Generated by Django 5.1.2 on 2025-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_termreporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
