# Generated by Django 5.1.2 on 2025-03-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
