# Generated by Django 5.1.2 on 2025-03-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='class_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.class_of_study'),
        ),
    ]
