# Generated by Django 5.1.2 on 2025-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_cat_class_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='profile_image',
            field=models.ImageField(blank=True, default='intern_profiles/profile.png', null=True, upload_to='intern_profiles/'),
        ),
    ]
