# Generated by Django 5.1.2 on 2025-03-25 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_intern_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('assignment_file', models.FileField(help_text='Upload assignment PDF (PDF only)', upload_to='assignments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('collection_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.class_of_study')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.term')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
                'unique_together': {('class_of_study', 'subject', 'term', 'title')},
            },
        ),
    ]
